const fs = require("fs");
const path = require("path");
const opentype = require("opentype.js");

const FIRST = 32;
const LAST = 126;
const SS = 4;

function flattenPath(commands) {
  const contours = [];
  let cur = [];
  let cx = 0;
  let cy = 0;
  let sx = 0;
  let sy = 0;

  const lineTo = (x, y) => {
    cur.push([x, y]);
    cx = x;
    cy = y;
  };
  const cubic = (x1, y1, x2, y2, x, y) => {
    const N = 10;
    for (let i = 1; i <= N; i++) {
      const t = i / N;
      const mt = 1 - t;
      const a = mt * mt * mt;
      const b = 3 * mt * mt * t;
      const c = 3 * mt * t * t;
      const d = t * t * t;
      lineTo(a * cx + b * x1 + c * x2 + d * x, a * cy + b * y1 + c * y2 + d * y);
    }
    cx = x;
    cy = y;
  };
  const quad = (x1, y1, x, y) => {
    const N = 8;
    const x0 = cx;
    const y0 = cy;
    for (let i = 1; i <= N; i++) {
      const t = i / N;
      const mt = 1 - t;
      lineTo(mt * mt * x0 + 2 * mt * t * x1 + t * t * x, mt * mt * y0 + 2 * mt * t * y1 + t * t * y);
    }
    cx = x;
    cy = y;
  };

  for (const c of commands) {
    if (c.type === "M") {
      if (cur.length) contours.push(cur);
      cur = [[c.x, c.y]];
      cx = c.x;
      cy = c.y;
      sx = c.x;
      sy = c.y;
    } else if (c.type === "L") {
      lineTo(c.x, c.y);
    } else if (c.type === "C") {
      cubic(c.x1, c.y1, c.x2, c.y2, c.x, c.y);
    } else if (c.type === "Q") {
      quad(c.x1, c.y1, c.x, c.y);
    } else if (c.type === "Z") {
      lineTo(sx, sy);
      if (cur.length) contours.push(cur);
      cur = [];
    }
  }
  if (cur.length) contours.push(cur);
  return contours;
}

function windingAt(contours, px, py) {
  let wn = 0;
  for (const c of contours) {
    for (let i = 0; i < c.length - 1; i++) {
      const [ax, ay] = c[i];
      const [bx, by] = c[i + 1];
      if (ay <= py) {
        if (by > py) {
          const cross = (bx - ax) * (py - ay) - (px - ax) * (by - ay);
          if (cross > 0) wn++;
        }
      } else {
        if (by <= py) {
          const cross = (bx - ax) * (py - ay) - (px - ax) * (by - ay);
          if (cross < 0) wn--;
        }
      }
    }
  }
  return wn;
}

function rasterizeFont(font, sizePx) {
  const scale = sizePx / font.unitsPerEm;
  const glyphs = [];
  const coverage = [];
  let offset = 0;

  for (let code = FIRST; code <= LAST; code++) {
    const ch = String.fromCharCode(code);
    const glyph = font.charToGlyph(ch);
    const advance = Math.round((glyph.advanceWidth || 0) * scale);
    const p = glyph.getPath(0, 0, sizePx);
    const bb = p.getBoundingBox();

    if (!isFinite(bb.x1) || bb.x2 <= bb.x1 || bb.y2 <= bb.y1) {
      glyphs.push({ offset, w: 0, h: 0, adv: advance, xo: 0, yo: 0 });
      continue;
    }

    const x1 = Math.floor(bb.x1);
    const y1 = Math.floor(bb.y1);
    const x2 = Math.ceil(bb.x2);
    const y2 = Math.ceil(bb.y2);
    const w = x2 - x1;
    const h = y2 - y1;
    const contours = flattenPath(p.commands);

    for (let yy = 0; yy < h; yy++) {
      for (let xx = 0; xx < w; xx++) {
        let inside = 0;
        for (let sy = 0; sy < SS; sy++) {
          for (let sx = 0; sx < SS; sx++) {
            const px = x1 + xx + (sx + 0.5) / SS;
            const py = y1 + yy + (sy + 0.5) / SS;
            if (windingAt(contours, px, py) !== 0) inside++;
          }
        }
        coverage.push(Math.round((inside / (SS * SS)) * 255));
      }
    }

    glyphs.push({ offset, w, h, adv: advance, xo: x1, yo: y1 });
    offset += w * h;
  }

  const yAdvance = Math.round(((font.ascender - font.descender) / font.unitsPerEm) * sizePx);
  return { glyphs, coverage, yAdvance, sizePx };
}

function emit(name, baked) {
  const cov = baked.coverage;
  let s = "static const uint8_t " + name + "_COV[] = {\n";
  for (let i = 0; i < cov.length; i += 20) {
    s += "  " + cov.slice(i, i + 20).join(", ") + ",\n";
  }
  s += "};\n\n";
  s += "static const AAGlyph " + name + "_GLYPHS[] = {\n";
  baked.glyphs.forEach((g) => {
    s += "  {" + g.offset + ", " + g.w + ", " + g.h + ", " + g.adv + ", " + g.xo + ", " + g.yo + "},\n";
  });
  s += "};\n\n";
  s += "const AAFont " + name + " = {" + name + "_COV, " + name + "_GLYPHS, " + FIRST + ", " + LAST + ", " + baked.yAdvance + ", " + baked.sizePx + "};\n\n";
  return s;
}

function main() {
  const ttf = process.argv[2];
  const out = process.argv[3];
  if (!ttf || !out) {
    console.error("usage: node gen_aafont.js <font.ttf> <out.h>");
    process.exit(1);
  }
  const font = opentype.loadSync(ttf);

  const body = rasterizeFont(font, 15);
  const title = rasterizeFont(font, 24);

  let h = "#ifndef LUCARNE_FONT_DEFAULT_H\n#define LUCARNE_FONT_DEFAULT_H\n\n";
  h += "// Generated by scripts/gen_aafont.js from " + path.basename(ttf) + "\n";
  h += '#include "../../core/LucarneFont.h"\n\n';
  h += "namespace lucarne {\n\n";
  h += emit("LucarneFontBody", body);
  h += emit("LucarneFontTitle", title);
  h += "}\n\n#endif\n";

  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, h);
  const kb = (body.coverage.length + title.coverage.length) / 1024;
  console.log("Wrote " + out + " (~" + kb.toFixed(1) + " KB coverage)");
}

main();
